"""Language helpers for HTML rendering.

The `lib.visualisering.lang` package contains:

- `translations.py`  — `t(key, lang)` helper backed by a dict-based table.
- `da/`              — Danish components (the default, mostly empty so we
                       fall back to ``lib/visualisering/components``).
- `en/`              — English-translated components.

The HTML renderer picks the language directory based on a flag and looks
for components there first; missing components fall back to Danish.

Construction-specific text (the actual recipe) is generated by the
``constructions/*.py`` modules. They go through ``t(key, lang)`` for
fixed labels (e.g. round numbers, decrease/increase labels), but
geometry-derived prose stays in Danish unless the construction explicitly
emits an English variant.
"""

from .translations import t, available_languages, register_translations

__all__ = ["t", "available_languages", "register_translations"]
